### ISSUE TITLE
About the scored_summaries in AbstractiveFusionDataset

### ISSUE THREAD

**Issue by AnhLD2610** [Ravoxsg/SummaFusion#1]
I found that in your data set training for SummaFusion i see that the AbstractiveFusionDataset has score attributes but in the paper you don't mention about score, i thought that only Source and Summary Candidates is input for Second-stage why it's has score too and what is that score, could you figure me out?

**Comment by Ravoxsg** [comment]
Hello @AnhLD2610 and thanks for your interest in our work!
The summary candidate scores are used to train the classification component of SummaFusion. This follows the same principle as in SummaReranker: it's a binary classification where the positive(s) candidates are the ones with the highest score (e.g, ROUGE-1). All the other candidates are negative. Please see SummaFusion's paper Section 3.2, where this is described. 
These scores are not used when running **inference** with SummaFusion, as the classification component is discarded at inference time.

**Comment by AnhLD2610** [comment]
Thank you for your detailed reply!
